name: App Testing

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: "16.x"
        cache: "npm"
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: Upload Test Video
      uses: actions/upload-artifact@v2
      with:
        name: test-video
        path: cypress/videos
