name: Build & Integration Testing

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: "16.x"
        cache: "npm"
    - run: npm ci
    - name: Build Tests
      run: |
        npm install -g ionic
        npm run build
        ionic cap sync
    - name: Integration Tests
      run: |
        npm install -g serve
        serve -s build -p 8100 &
        npm run test
    - name: Upload Test Video
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: test-video
        path: cypress/videos
